/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcp.client.view;

import tcp.client.control.ClientCtr;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Group;
import model.ObjectWrapper;
import model.Player;
import model.PlayerGroup;

/**
 *
 * @author fake1
 */
public class GroupInfoFrm extends javax.swing.JFrame {
    private ClientCtr myControl;
    private Player myPlayer;
    private Group group;
    /**
     * Creates new form GroupFrm
     */
    public GroupInfoFrm(ClientCtr myControl) {
        initComponents();
        this.myControl = myControl;
        myControl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_GET_PLAYERS_WANT_JOIN_GROUP, this));
    }
    
    public void setGroupInfoFrm(Player player, Group group, ClientCtr myControl){
        
        this.myPlayer = player;
        this.group = group;
        this.myControl = myControl;
        jLabel1.setText(group.getName());
        jLabel2.setText("Username: "+player.getUsername());
        jTextAreaGroupNote.append(group.getNote());
        viewInit();
    }

    public void viewInit(){
        ArrayList<PlayerGroup> playerGroupList = group.getPlayerGroupList();
        String[] columnNames={"Username ","Rank ","Role ","Status"};
            String[][] value=new String[playerGroupList.size()][4];
            for(int i=0;i<playerGroupList.size();i++)
            {
                
                Player player = playerGroupList.get(i).getPlayer();
                value[i][0]= player.getUsername();
                switch (playerGroupList.get(i).getRole()){
                    case PlayerGroup.MEM:
                        value[i][2]= "Member";  
                        break;
                    case PlayerGroup.MOD:
                        value[i][2]= "Moderator";
                        break;
                }
                
                switch (player.getStatus()){
                    case Player.ONLINE:
                        value[i][3]= "online";
                        break;
                    case Player.OFFLINE:
        		value[i][3]= "offline ";
        		break;
                    case Player.PLAYING:
        		value[i][3]= "playing";
        		break;
                }
                

            }
        tblGroup.setModel(new DefaultTableModel(value,columnNames));
        
    }
    
    public void receivedDataProcessing(ObjectWrapper data){
        if (data.getPerformative() == ObjectWrapper.REPLY_GET_PLAYERS_WANT_JOIN_GROUP){
            WantJoinGroupFrm joinView = new WantJoinGroupFrm(group.getId(), (ArrayList<Player>)data.getData(), myControl);
            
            joinView.setLocationRelativeTo(this);
            joinView.setVisible(true);
            this.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAddMem = new javax.swing.JButton();
        jButtonOutGroup = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaGroupNote = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGroup = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("group name");

        jButtonAddMem.setText("Duyệt thành viên");
        jButtonAddMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMemActionPerformed(evt);
            }
        });

        jButtonOutGroup.setText("Thoát group");
        jButtonOutGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutGroupActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextAreaGroupNote.setColumns(20);
        jTextAreaGroupNote.setRows(5);
        jTextAreaGroupNote.setText("Thông báo:\n");
        jScrollPane2.setViewportView(jTextAreaGroupNote);

        jLabel2.setText("You");

        tblGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Rank", "Role"
            }
        ));
        tblGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGroup);

        jTabbedPane1.addTab("Memeber", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButtonAddMem)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonOutGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCancel))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonAddMem)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel)
                            .addComponent(jButtonOutGroup)))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void tblGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupMouseClicked
        // TODO add your handling code here:
        int r = tblGroup.getSelectedRow();
        if (r>=0 && r< tblGroup.getRowCount()){
            Player plr = group.getPlayerGroupList().get(r).getPlayer();
            PlayerInfoFrm playerView = new PlayerInfoFrm(plr, myControl, myPlayer.searchFriendbyId(plr.getId()),myPlayer.getId(),myPlayer.getGroupList());
            playerView.setLocationRelativeTo(this);
            playerView.setVisible(true);
        }
    }//GEN-LAST:event_tblGroupMouseClicked

    private void jButtonAddMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMemActionPerformed
        // TODO add your handling code here:
        myControl.sendData(new ObjectWrapper(ObjectWrapper.GET_PLAYERS_WANT_JOIN_GROUP,group.getId()));
    }//GEN-LAST:event_jButtonAddMemActionPerformed

    private void jButtonOutGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutGroupActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn rời khỏi group ?");
        if(ans == 0){
            PlayerGroup pg = new PlayerGroup();
            pg.setPlayer(myPlayer);
            pg.setGroup(group);
            myControl.sendData(new ObjectWrapper(ObjectWrapper.OUT_GROUP, pg));
            this.dispose();
        }
    }//GEN-LAST:event_jButtonOutGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupInfoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupInfoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupInfoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupInfoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GroupInfoFrm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMem;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOutGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaGroupNote;
    private javax.swing.JTable tblGroup;
    // End of variables declaration//GEN-END:variables
}
