/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tcp.client.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ObjectWrapper;
import model.Player;
import model.Request;
import tcp.client.control.ClientCtr;

/**
 *
 * @author fake1
 */
public class WantJoinGroupFrm extends javax.swing.JFrame {
    private ClientCtr myControl;
    private ArrayList<Player> playerWantJoinList;
    private int groupId;
    /**
     * Creates new form WantJoinGroupFrm
     */
    public WantJoinGroupFrm() {
        initComponents();
    }
    
    public WantJoinGroupFrm(int groupId, ArrayList<Player> playerWantJoinList, ClientCtr myControl) {
        initComponents();
        this.groupId = groupId;
        this.playerWantJoinList = playerWantJoinList;
        this.myControl = myControl;
        viewInit();
    }
    
    public void viewInit(){
        String[] columnNames={"Username ","Win match ","Total match "};
            String[][] value=new String[playerWantJoinList.size()][3];
            for(int i=0;i<playerWantJoinList.size();i++)
            {
                value[i][0]= playerWantJoinList.get(i).getUsername();
                value[i][1]= playerWantJoinList.get(i).getWinmatch()+"";
                value[i][2]= playerWantJoinList.get(i).getTotalmatch()+"";
            }
        tblJoin.setModel(new DefaultTableModel(value,columnNames));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJoin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblJoin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJoinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJoin);

        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJoinMouseClicked
        // TODO add your handling code here:
        int r = tblJoin.getSelectedRow();
        if (r>=0 && r<tblJoin.getRowCount()){
            Player plr = playerWantJoinList.get(r);
            int response = JOptionPane.showConfirmDialog(this,"Bạn có đồng ý cho "+ plr.getUsername() +" vào nhóm" , "Y/N", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(response){
                case JOptionPane.YES_OPTION:
                    myControl.sendData(new ObjectWrapper(ObjectWrapper.ACCEPT_JOIN_REQUEST,new Request(plr.getId(),groupId)));
//                    ObjectWrapper rdata = myControl.receiveData();
//                    if (rdata.getPerformative()== ObjectWrapper.REPLY_ACCEPT_JOIN_REQUEST){
//                        if (rdata.getData().equals("ok")){
//                            JOptionPane.showMessageDialog(this, "Success");
                            this.dispose();
//                        
//                        }
//                        else JOptionPane.showMessageDialog(this, "Error");   
//                    }
                    break;
                    
                case JOptionPane.NO_OPTION:
                    myControl.sendData(new ObjectWrapper(ObjectWrapper.REJECT_JOIN_REQUEST,new Request(plr.getId(),groupId)));
//                    rdata = myControl.receiveData();
//                    if (rdata.getPerformative()== ObjectWrapper.REPLY_REJECT_FRIEND_REQUEST){
//                        if (rdata.getData().equals("ok")){
//                            JOptionPane.showMessageDialog(this, "Success");
                            this.dispose();
//                        }
//                        else JOptionPane.showMessageDialog(this, "Error");   
//                    }
                    break;
                    
            }
        }
    }//GEN-LAST:event_tblJoinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WantJoinGroupFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WantJoinGroupFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WantJoinGroupFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WantJoinGroupFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WantJoinGroupFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJoin;
    // End of variables declaration//GEN-END:variables
}
